### ISSUE TITLE
`maximum_adjacency_search`: dead code, broken `assignments` parameter, missing contraction support

### ISSUE THREAD

**Issue by sebrockm** [boostorg/graph#297]
There are several things wrong with `maximum_adjacency_search`:

- The pseudo code on https://www.boost.org/doc/libs/1_79_0/libs/graph/doc/maximum_adjacency_search.html does not mention any weights. Yet, `weights` is a required parameter. It's unclear what it is doing.
- In [L127](https://github.com/boostorg/graph/blob/430f61f6962614bb33fe7be3b054229953803ced/include/boost/graph/maximum_adjacency_search.hpp#L127), there is a `set` defined, but it is never filled with any values. In [L181](https://github.com/boostorg/graph/blob/430f61f6962614bb33fe7be3b054229953803ced/include/boost/graph/maximum_adjacency_search.hpp#L181) there is a loop iterating over this always empty `set`. This is dead code.
- It looks like the `assignments` property map is a dead parameter. Looking at the implementation, in [L131](https://github.com/boostorg/graph/blob/430f61f6962614bb33fe7be3b054229953803ced/include/boost/graph/maximum_adjacency_search.hpp#L131) we see the one and only `put` operation performed on it. It overrides all possibly provided user input and assigns every vertex to itself. That makes all following `get` operations obsolete (every `get(assignments, x)` is equivalent to just `x`).
- [L158](https://github.com/boostorg/graph/blob/430f61f6962614bb33fe7be3b054229953803ced/include/boost/graph/maximum_adjacency_search.hpp#L158) is a noop

### Background:
This algorithm was introduced in https://github.com/boostorg/graph/commit/393c072c186f6711d1537225dc116ea1528140ac. There, it was extracted from `stoer_wagner_min_cut` which caused #286.

**Comment by jeremy-murphy** [comment]
Interesting. Thanks for looking into it! You've certainly identified some serious issues with that implementation.

The next big question would be, do the existing unit tests cover everything? If they do, then someone can be free to refactor the hell out of that implementation. But I can only imagine that it is going to require some additional tests to cover the obviously wrong behaviour on `assignments`, etc.

The existing unit tests are moderately complicated; if someone wants to tackle this, I'd recommend adding some ultra-simple ones too.

**Comment by daank94** [comment]
Hey, I had a look at this as well. I'm not sure about the correctness of the pseudo-code/algorithm in the documentation (https://www.boost.org/doc/libs/1_82_0/libs/graph/doc/maximum_adjacency_search.html). Could either of you check whether this is correct?
Based on the original research paper from "A linear time 2 + epsilon approximation algorightm for edge connectivity" (as linked in the documentation), I came up with the following pseudocode, which does differ from the documentation:

```
nodes_visited = set()
node_k_values = map<node, long>
prio_queue = [start_node]

// The results of the algorithm, a list of nodes in order + k values for each edge
node_order = []
edge_k_values = map<edge, long>

while priority queue not empty {
// Pop the node with highest k value
// Then update k-values of neighbour nodes
k_value, node = pq.pop() // Get top element and remove from prio queue

if nodes_visited.contains(top_node) {
	continue
}

nodes_visited.add(top_node)

node_order.push_back(top_node)

for edge, neighour_node in top_node.neighbours() {

	node_k_values[neighbour_node]++
	edge_k_values[neighbour_node] = node_k_values[neighbour_node]
	pq.push_back(node_k_values[neighbour_node], neighbour_node)
}
}
```

Please let me know what you think. I am going to take a look at the unit tests and/or maybe write some tests myself to verify the above algorithm.

**Comment by jeremy-murphy** [comment]
It took me a while of reading the documentation for this to realize that MAS is not an algorithm per se but another search strategy like BFS and DFS. That documentation could do with some nice graphs that show the sequence of the search, etc, and ultimately I would categorize this along with BFS and DFS in the table of contents, changing the category from "Core Searches" to just "Search". (As an aside "A* search" is not really a search, so it's fine where it is.)

Anyway, the way forward is to make the unit tests watertight first so that then you can go to town changing the implementation. I wouldn't worry too much about the pseudocode for now.

**Comment by daankolthof** [comment]
Great, I'm working on the unit tests right now. I'm expanding the existing ones and making new ones for simple and complex graphs.
I'll try to have a PR ready before the end of next week.

**Comment by daankolthof** [comment]
Hey @jeremy-murphy, @sebrockm (and others), I have created https://github.com/boostorg/graph/pull/333 which refactors the existing tests and creates many new ones. Please let me know what you think.

**Comment by daankolthof** [comment]
Also on the `weights` parameter: every edge in the graph contains a weight. In the simplest case, this can be 1 for every edge.
MAS searching through the graph is done based on priority. The weights of each edge determine the priority of unvisited nodes. E.g., when node A is visited and edge A-B has priority 10, node B's priority in the queue will be increased by 10.

**Comment by andreacassioli** [comment]
I guess this issue is resolved, isn't it?

**Comment by jeremy-murphy** [comment]
I'm not so sure. I just quickly went through the linked issues and pull requests, and it looks like the problems with MAS have been mitigated but not fixed. That is, we stopped using it as the basis of other algorithms, but MAS itself still needs fixing if we're ever going to use it. Anyone else able to confirm?

**Comment by andreacassioli** [comment]
I can see at least issues 2, 3, and 4 are still there.

**Comment by jeremy-murphy** [comment]
Anyone interested in doing more work on this?

**Comment by Becheler** [comment]
I can pick it up 😃

**Comment by Becheler** [comment]
I merged a bunch of PRs that together fix the different complains and others.
1. Expand test coverage for MAS and SW to make sure we don't break anything
2. Add new overloads of `boost::graph::maximum_adjacency_search` and deprecate `boost::maximum_adjacency_search` overloads
3. Rewires Stoer-Wagner internals to use the same algorithm as MAS (no code duplication)
4. Add MAS support for stateful visitors passed by `std::reference_wrapper`
5. Update documentation: https://www.boost.org/doc/libs/develop/libs/graph/doc/html/graph/algorithms/utility/maximum_adjacency_search.html

The new MAS overloads don't mention the contraction and assignments. They call a `detail::mas_sweep` implementation that maintains those arguments and MAS defaults them for no effect. The Stoer Wagner however calls this sweep with arguments that triggers the contraction. I did not make `mas_sweep` public because it's hard to guarantee preconditions and there is no demande so far for it. 

 This should now be complete, but let me know in case something slipped my mind 😄
